### ISSUE TITLE
Support for Eldom Smart boilers

### ISSUE THREAD

**Issue by danielgospodinow** [qbaware/homeassistant-eldom#13]
Like [this](https://eldominvest.com/en/product/502.html) one.

**Comment by jeroenb21** [comment]
This would be great! Tried to adjust the current version by changing flat by smart and referring to the 0.2.0 package but I get an error and I don't have the knowledge to solve it.

**Comment by juras72** [comment]
Hello, and what about the heaters like that: https://eldominvest.com/en/category/20.html

I will buy you more than 1 beer :)

Cheeers,
Juraj

**Comment by danielgospodinow** [comment]
@juras72, I'd love to support those as well! 😄 The only problem is that I cannot get a hold of the APIs for those devices. 😕 I tried reaching out to Naturela (the developers of those APIs), but they weren't super keen on giving me some docs.

**Comment by danielgospodinow** [comment]
@jeroenb21, I just released [1.0.0](https://github.com/qbaware/homeassistant-eldom/releases/tag/1.0.0) and I added support for smart boilers.

Can you try out the integration and let me know if it works well for you?

**Comment by danielgospodinow** [comment]
@juras72, I'll reopen a new issue requesting support for the devices that you've shown.

**Comment by danielgospodinow** [comment]
This issue is resolved with [1.0.0](https://github.com/qbaware/homeassistant-eldom/releases/tag/1.0.0).

**Comment by jeroenb21** [comment]
> @jeroenb21, I just released [1.0.0](https://github.com/qbaware/homeassistant-eldom/releases/tag/1.0.0) and I added support for smart boilers.
> 
> Can you try out the integration and let me know if it works well for you?

Hi Daniel,
I installed the newer version, it says 2.0.0 ? 
I can login now and see the boiler. But there is not a lot I can do with it. Only some consumption numbers. 
<img width="1192" alt="Scherm­afbeelding 2024-11-17 om 18 59 34" src="https://github.com/user-attachments/assets/b8ac5572-04fb-4061-96e4-468f0564f289">

**Comment by danielgospodinow** [comment]
Hi, @jeroenb21! 

Oh, that's interesting. You should also see the water heater entity itself. 😕 

I'm testing with the following smart boiler: https://eldominvest.com/bg/product/502.html 

I'm getting this functionality:

<img width="1660" alt="image" src="https://github.com/user-attachments/assets/e762bd82-b087-4047-bb68-053db6d29a53">

<img width="1661" alt="image" src="https://github.com/user-attachments/assets/14fd6696-b05f-48ee-bbef-8fc8a6f4fe2c">

The functionalities are:
- Water heater entity functionalities
- Powerful mode enabling
- Sensor data (that you already see)

Can you try updating the integration again? I just pushed a minor version to fix two smart boiler API calls that I had mistaken. And let me know if it works well this time.

**Comment by jeroenb21** [comment]
Hi @danielgospodinow,
I edited the above comment but I see it doesnt really show. But after a hour it was working like it should. 
Thank you !

**Comment by jeroenb21** [comment]
Hi Daniel,
I got this message when adjusting the tempreture. Seems its looking at the wrong url.
<img width="671" alt="Scherm­afbeelding 2024-11-19 om 12 29 51" src="https://github.com/user-attachments/assets/8ec60de0-47f2-4370-a106-24891c3e19c8">

**Comment by danielgospodinow** [comment]
@jeroenb21, yes, that's correct. I had a bug a while back that's fixed now. Can you try and update to the latest version? It's `2.2.3`. The issue should no longer be there.
