### ISSUE TITLE
Support for Eldom convection heaters

### ISSUE THREAD

**Issue by danielgospodinow** [qbaware/homeassistant-eldom#17]
Like [those](https://eldominvest.com/en/category/20.html).

The request has been raised by @juras72 in https://github.com/qbaware/homeassistant-eldom/issues/13. 

The current blocker is that I have no idea what the management APIs look like.

**Comment by danielgospodinow** [comment]
@juras72, do you mind cooperating with me and providing me with an API doc so that I can add support for those devices?

**Comment by maslyankov** [comment]
Can this help - https://github.com/X-Terminator/home-assistant-eldom-integration/tree/main ?

**Comment by danielgospodinow** [comment]
@maslyankov, cool! I wasn't aware that there's an existing Eldom integration 😅 Even though I was looking quite hard for one.

**Comment by danielgospodinow** [comment]
With https://github.com/qbaware/homeassistant-eldom/commit/ad70adf54a9073a2fa1771bd09e8b3be069a9856, experimental support for convection heaters is added.

@juras72, can you check if it works for you?
