### ISSUE TITLE
Add boiler consumption to energy dashboard 

### ISSUE THREAD

**Issue by Kaxrr** [qbaware/homeassistant-eldom#22]
Hi, 
there are two energy consumption entities (day, night) with eldom boilers that could be added as individual consumption to the ha energy dashboard. 
For now the entities are non visible.
Is it because of the missing state class?
Thanks

**Comment by danielgospodinow** [comment]
@Kaxrr, as of now, I'm not really familiar with HA's Energy dashboard and how it works. 

I'll do my research and try to implement this.

I'll update here when I have news.

**Comment by danielgospodinow** [comment]
You were right, @Kaxrr! The missing state class was the problem.

From what I understood form the [docs](https://developers.home-assistant.io/docs/core/entity/sensor/#how-to-choose-state_class-and-last_reset), it looks to me that the right state class should be `SensorStateClass.TOTAL_INCREASING` for both supported water boilers (`flat` and `smart`).

I've added appropriate state classes with [3.2.0](https://github.com/qbaware/homeassistant-eldom/releases/tag/3.2.0). Hope this helps you.

**Comment by Kaxrr** [comment]
Yes, it is much better now.thank you!
